FROM base/archlinux

RUN pacman -Sy

# prep/test dependencies
RUN pacman -S --noconfirm \
    base-devel openssh python python-pip python-ddt

# dups system dependencies
RUN pacman -S  --noconfirm \
    rsync dbus libnotify python-gobject

# dups python requirements
RUN pacman -S --noconfirm \
    python-dbus python-paramiko python-ruamel-yaml

COPY tests/.ssh /root/.ssh
RUN chmod -R 700 /root/.ssh

RUN mkdir /var/run/sshd
RUN /usr/bin/ssh-keygen -A
