#!/usr/bin/env sh

cd "$(dirname "$0")"

DUPS="../../run"
README="../../README.md"
TEMPLATE="../../README-template.md"

data=$(cat "$TEMPLATE")

# Replace tags within the template
help_text=$($DUPS -h)
data="${data/"[[ help ]]"/$help_text}"

req_sys=$(cat "../../dependencies.txt")
data="${data/"[[ req-sys ]]"/$req_sys}"

req_py=$(cat "../../requirements.txt")
data="${data/"[[ req-py ]]"/$req_py}"

# Upate the README
echo "$data" > "$README"
